#!/usr/bin/env python3
"""Emit idempotent PostgreSQL seed SQL for the transcribed WOK recipe book."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def sql(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def source_status(value: str) -> str:
    return {
        "transcrito": "TRANSCRIBED",
        "por_confirmar": "PENDING_CONFIRMATION",
        "por_confirmar_unidad": "PENDING_UNIT",
        "confirmado_usuario": "USER_CONFIRMED",
    }.get(value, "PENDING_CONFIRMATION")


def validate(data: dict[str, Any]) -> None:
    if data.get("schema_version") != 1:
        raise ValueError("Unsupported recipe book schema_version")
    ids: set[str] = set()
    for collection in ("recipes", "purchases", "questions"):
        for row in data.get(collection, []):
            key = row.get("id")
            if not key or key in ids:
                raise ValueError(f"Missing or duplicate source id: {key!r}")
            ids.add(key)
    for recipe in data.get("recipes", []):
        if recipe.get("yield_quantity") is not None or recipe.get("yield_unit") is not None:
            raise ValueError(f"Draft yield must remain NULL: {recipe['id']}")
        if recipe.get("procedure") is not None or recipe.get("preparation_minutes") is not None:
            raise ValueError(f"Draft procedure/time must remain NULL: {recipe['id']}")
        for item in recipe.get("ingredients", []):
            if item.get("quantity") is not None and float(item["quantity"]) <= 0:
                raise ValueError(f"Non-positive quantity in {recipe['id']}")


def generate(data: dict[str, Any]) -> str:
    validate(data)
    out = [
        "-- Generated by scripts/db/import_recipe_book.py; safe to re-run.",
        "BEGIN;",
        "SET search_path = wok, public;",
        "",
        "-- Link only unambiguous exact-name matches; keep uncertain products for review.",
    ]
    # The mapping is intentionally conservative. The recipe book's generic
    # 'Cerdo' and 'Ramen' names are not silently equated with sale products.
    aliases = {
        "Cerdo": "Cerdo agridulce",
        "Pollo naranja": "Pollo a la naranja",
        "Ramen": "Miso Ramen",
        "Ura aguacate": "Uramaki Aguacate",
        "Ura atún": "Uramaki Atún",
        "Ura salmón": "Uramaki Salmón",
        "Onigiri": "Onigiris",
    }
    for recipe in data["recipes"]:
        name = aliases.get(recipe["name"], recipe["name"])
        normalized = name.casefold().strip()
        requires_review = recipe["name"] in {"Cerdo", "Ramen"}
        # Explicit output name is included as a scalar; SQL checks uniqueness.
        out.append(
            "INSERT INTO recipe_book_recipes (source_id, output_menu_item_id, name, source, status, link_status, note, yield_quantity, yield_unit, procedure, preparation_minutes)\n"
            f"SELECT {sql(recipe['id'])}, (SELECT (array_agg(mi.id))[1] FROM menu_items mi WHERE lower(btrim(mi.name)) = lower(btrim({sql(normalized)})) HAVING count(*) = 1), "
            f"{sql(recipe['name'])}, {sql(recipe['source'])}, 'PENDING_VALIDATION', "
            f"CASE WHEN NOT {sql(requires_review)} AND (SELECT count(*) FROM menu_items mi WHERE lower(btrim(mi.name)) = lower(btrim({sql(normalized)}))) = 1 THEN 'LINKED' ELSE 'NEEDS_REVIEW' END, "
            f"{sql(recipe.get('note') or '')}, NULL, NULL, NULL, NULL\n"
            "ON CONFLICT (source_id) DO NOTHING;"
        )
        for index, ingredient in enumerate(recipe["ingredients"], start=1):
            component_id = f"{recipe['id']}-{index:03d}"
            confirmation = ingredient.get("confirmation_source")
            out.append(
                "INSERT INTO recipe_book_components (source_id, recipe_id, ingredient_item_id, ingredient_name, quantity, unit_code, raw, source, note, status, confirmation_source, alternate_quantity, alternate_unit_code)\n"
                f"SELECT {sql(component_id)}, r.id, (SELECT (array_agg(i.id))[1] FROM items i WHERE lower(btrim(i.name)) = lower(btrim({sql(ingredient['ingredient'])})) HAVING count(*) = 1), "
                f"{sql(ingredient['ingredient'])}, {sql(ingredient.get('quantity'))}, {sql(ingredient['unit'])}, {sql(ingredient.get('raw') or '')}, {sql(recipe['source'])}, "
                f"{sql(ingredient.get('note') or '')}, {sql(source_status(ingredient.get('status', '')))}, {sql(confirmation)}, "
                f"{sql(ingredient.get('alternative_quantity'))}, {sql(ingredient.get('alternative_unit'))}\n"
                f"FROM recipe_book_recipes r WHERE r.source_id = {sql(recipe['id'])}\n"
                "ON CONFLICT (source_id) DO NOTHING;"
            )
    for purchase in data["purchases"]:
        out.append(
            "INSERT INTO recipe_book_purchases (source_id, ingredient_item_id, ingredient_name, presentation, quantity, unit_code, raw, source, note, status, confirmation_source, alternate_quantity, alternate_unit_code, is_inventory)\n"
            f"SELECT {sql(purchase['id'])}, (SELECT (array_agg(i.id))[1] FROM items i WHERE lower(btrim(i.name)) = lower(btrim({sql(purchase['ingredient'])})) HAVING count(*) = 1), "
            f"{sql(purchase['ingredient'])}, {sql(purchase['presentation'])}, {sql(purchase.get('quantity'))}, {sql(purchase['unit'])}, {sql(purchase.get('raw') or '')}, "
            f"{sql(purchase.get('source') or '')}, {sql(purchase.get('note') or '')}, {sql(source_status(purchase.get('status', '')))}, "
            f"{sql(purchase.get('confirmation_source'))}, {sql(purchase.get('alternative_quantity'))}, {sql(purchase.get('alternative_unit'))}, FALSE\n"
            "ON CONFLICT (source_id) DO NOTHING;"
        )
    for question in data["questions"]:
        answer = question.get("answer")
        out.append(
            "INSERT INTO recipe_book_questions (source_id, topic, question, answer, status) VALUES ("
            f"{sql(question['id'])}, {sql(question['topic'])}, {sql(question['question'])}, {sql(answer)}, "
            f"{'\'ANSWERED\'' if answer else '\'OPEN\''}) ON CONFLICT (source_id) DO NOTHING;"
        )
    out.extend(["COMMIT;", ""])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Canonical wok_recetario_datos.json")
    args = parser.parse_args()
    try:
        data = json.loads(args.input.read_text(encoding="utf-8"))
        print(generate(data), end="")
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"recipe book import: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
