export const homeCopy = {
  heroLabel: "Hoy se antoja",
  heroFallbackTitle: "Humeante, crujiente, irresistible.",
  heroSubtitle: "El sabor de Asia, a minutos de tu mesa.",
  orderAction: "Pedir ahora",
  brandImage: "WOK Asian Food",
  greeting: "Hola, bienvenido a WOK",
  returningGreeting: "Qué gusto verte de nuevo",
  carouselTitle: "Los más antojables",
  carouselLoading: "Cargando platillos",
  menuError: "No pudimos cargar el menú. Intenta de nuevo.",
  menuEmpty:
    "Tu próximo antojo está en camino. Vuelve a consultar el menú más tarde.",
  menuAction: "Ver todo el menú",
  retry: "Reintentar",
  shortcuts: { menu: "Menú", reservations: "Reservar", orders: "Mis pedidos" },
  statusTitle: "Antes de visitarnos",
  statusDescription:
    "Consulta los servicios publicados. El horario de atención no está disponible en esta aplicación.",
  statusLoading: "Consultando servicios",
  statusError: "No pudimos consultar el estado del restaurante.",
  statusEmpty: "El restaurante todavía no publicó servicios.",
  statusUnknown: "Estado no disponible",
  statusRetry: "Reintentar estado",
  statusRefresh: "Actualizar estado",
  contact: "Contacto",
  requestNotice:
    "Enviar una solicitud no confirma una reserva ni un pedido. El equipo te informará el resultado.",
  serviceNames: {
    LOCAL: "Servicio en el restaurante",
    RESERVATIONS: "Reservas",
    DINE_IN_ONLINE: "Pedidos en mesa",
    PICKUP: "Para recoger",
    ONLINE_ORDERS: "Pedidos en línea",
    MESSAGING: "Mensajes",
  } as Record<string, string>,
  statusNames: {
    ENABLED: "Disponible",
    MANUAL_APPROVAL: "Sujeto a confirmación",
    PAUSED: "Pausado",
    DISABLED: "No disponible",
  },
  detailLabel: (name: string, price: string) => `Ver ${name}, ${price}`,
  addLabel: (name: string) => `Agregar ${name} al carrito`,
};
